name: Markdown Linter

on:
  push:
    branches:
      - main

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3
      - name: Run Markdown Linter
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: "**/*.md"
    
