name: Auto Format Code with Prettier

on:
  push:
    branches:
      - main

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier on JavaScript and CSS files
        run: prettier --write "**/*.{js,css}"

      - name: Commit formatted files
        run: |
          git config --global user.name "github.actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-formatted code with Prettier" || echo "No changes to commit"
